swagger: '2.0'
info:
  version: '1.0'
  title: localhost:8000
host: localhost:8000
basePath: /wp-json
schemes:
  - http
consumes:
  - multipart/form-data
produces:
  - application/json
paths:
  /wp/v2/medicines:
    get:
      parameters:
        - name: context
          type: string
          in: query
          description: Scope under which the request is made; determines fields present in response.
          default: view
          enum:
            - view
            - embed
            - edit
        - name: page
          type: integer
          in: query
          description: Current page of the collection.
          default: 1
          minimum: 1
          format: number
        - name: per_page
          type: integer
          in: query
          description: Maximum number of items to be returned in result set.
          default: 10
          minimum: 1
          format: number
          maximum: 100
        - name: search
          type: string
          in: query
          description: Limit results to those matching a string.
        - name: after
          type: string
          in: query
          description: Limit response to posts published after a given ISO8601 compliant date.
          format: date-time
        - name: modified_after
          type: string
          in: query
          description: Limit response to posts modified after a given ISO8601 compliant date.
          format: date-time
        - name: author
          type: array
          in: query
          description: Limit result set to posts assigned to specific authors.
          items:
            type: string
        - name: author_exclude
          type: array
          in: query
          description: Ensure result set excludes posts assigned to specific authors.
          items:
            type: string
        - name: before
          type: string
          in: query
          description: Limit response to posts published before a given ISO8601 compliant date.
          format: date-time
        - name: modified_before
          type: string
          in: query
          description: Limit response to posts modified before a given ISO8601 compliant date.
          format: date-time
        - name: exclude
          type: array
          in: query
          description: Ensure result set excludes specific IDs.
          items:
            type: string
        - name: include
          type: array
          in: query
          description: Limit result set to specific IDs.
          items:
            type: string
        - name: menu_order
          type: integer
          in: query
          description: Limit result set to posts with a specific menu_order value.
        - name: offset
          type: integer
          in: query
          description: Offset the result set by a specific number of items.
        - name: order
          type: string
          in: query
          description: Order sort attribute ascending or descending.
          default: desc
          enum:
            - asc
            - desc
        - name: orderby
          type: string
          in: query
          description: Sort collection by post attribute.
          default: date
          enum:
            - author
            - date
            - id
            - include
            - modified
            - parent
            - relevance
            - slug
            - include_slugs
            - title
            - menu_order
        - name: slug
          type: array
          in: query
          description: Limit result set to posts with one or more specific slugs.
          items:
            type: string
        - name: status
          type: array
          in: query
          description: Limit result set to posts assigned one or more statuses.
          default: publish
          items:
            type: string
      security:
        - cookieAuth: []
      responses:
        '200':
          description: successful operation
          schema:
            type: array
            items:
              $ref: '#/definitions/medicines'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
      operationId: GetWpV2Medicines
    post:
      parameters:
        - name: date
          type: string
          in: formData
          description: The date the post was published, in the site's timezone.
          format: date-time
        - name: date_gmt
          type: string
          in: formData
          description: The date the post was published, as GMT.
          format: date-time
        - name: slug
          type: string
          in: formData
          description: An alphanumeric identifier for the post unique to its type.
        - name: status
          type: string
          in: formData
          description: A named status for the post.
          enum:
            - publish
            - future
            - draft
            - pending
            - private
        - name: password
          type: string
          in: formData
          description: A password to protect access to the content and excerpt.
        - name: title
          type: string
          in: formData
          description: The title for the post.
        - name: content
          type: string
          in: formData
          description: The content for the post.
        - name: author
          type: integer
          in: formData
          description: The ID for the author of the post.
        - name: featured_media
          type: integer
          in: formData
          description: The ID of the featured media for the post.
        - name: menu_order
          type: integer
          in: formData
          description: The order of the post in relation to other posts.
        - name: format
          type: string
          in: formData
          description: The format for the post.
          enum:
            - standard
            - aside
            - chat
            - gallery
            - link
            - image
            - quote
            - status
            - video
            - audio
        - name: template
          type: string
          in: formData
          description: The theme file to use to display the post.
      security:
        - cookieAuth: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/medicines'
        '201':
          description: successful operation
          schema:
            $ref: '#/definitions/medicines'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
      operationId: PostWpV2Medicines
  /wp/v2/medicines/{id}:
    get:
      parameters:
        - name: id
          type: string
          in: path
          required: true
        - name: id
          type: integer
          in: query
          description: Unique identifier for the post.
        - name: context
          type: string
          in: query
          description: Scope under which the request is made; determines fields present in response.
          default: view
          enum:
            - view
            - embed
            - edit
        - name: password
          type: string
          in: query
          description: The password for the post if it is password protected.
      security:
        - cookieAuth: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/medicines'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
      operationId: GetWpV2MedicinesById
    post:
      parameters:
        - name: id
          type: string
          in: path
          required: true
        - name: id
          type: integer
          in: formData
          description: Unique identifier for the post.
        - name: date
          type: string
          in: formData
          description: The date the post was published, in the site's timezone.
          format: date-time
        - name: date_gmt
          type: string
          in: formData
          description: The date the post was published, as GMT.
          format: date-time
        - name: slug
          type: string
          in: formData
          description: An alphanumeric identifier for the post unique to its type.
        - name: status
          type: string
          in: formData
          description: A named status for the post.
          enum:
            - publish
            - future
            - draft
            - pending
            - private
        - name: password
          type: string
          in: formData
          description: A password to protect access to the content and excerpt.
        - name: title
          type: string
          in: formData
          description: The title for the post.
        - name: content
          type: string
          in: formData
          description: The content for the post.
        - name: author
          type: integer
          in: formData
          description: The ID for the author of the post.
        - name: featured_media
          type: integer
          in: formData
          description: The ID of the featured media for the post.
        - name: menu_order
          type: integer
          in: formData
          description: The order of the post in relation to other posts.
        - name: format
          type: string
          in: formData
          description: The format for the post.
          enum:
            - standard
            - aside
            - chat
            - gallery
            - link
            - image
            - quote
            - status
            - video
            - audio
        - name: template
          type: string
          in: formData
          description: The theme file to use to display the post.
      security:
        - cookieAuth: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/medicines'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
      operationId: PostWpV2MedicinesById
    delete:
      parameters:
        - name: id
          type: string
          in: path
          required: true
        - name: id
          type: integer
          in: query
          description: Unique identifier for the post.
        - name: force
          type: boolean
          in: query
          description: Whether to bypass Trash and force deletion.
      security:
        - cookieAuth: []
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/medicines'
        default:
          description: error
          schema:
            $ref: '#/definitions/error'
      operationId: DeleteWpV2MedicinesById
definitions:
  error:
    properties:
      code:
        type: string
      message:
        type: string
      data:
        type: object
        properties:
          status:
            type: integer
  medicines:
    type: object
    properties:
      date:
        description: The date the post was published, in the site's timezone.
        type: string
        format: date-time
      date_gmt:
        description: The date the post was published, as GMT.
        type: string
        format: date-time
      guid:
        description: The globally unique identifier for the post.
        type: object
        properties:
          raw:
            description: GUID for the post, as it exists in the database.
            type: string
          rendered:
            description: GUID for the post, transformed for display.
            type: string
      id:
        description: Unique identifier for the post.
        type: integer
      link:
        description: URL to the post.
        type: string
        format: uri
      modified:
        description: The date the post was last modified, in the site's timezone.
        type: string
        format: date-time
      modified_gmt:
        description: The date the post was last modified, as GMT.
        type: string
        format: date-time
      slug:
        description: An alphanumeric identifier for the post unique to its type.
        type: string
      status:
        description: A named status for the post.
        type: string
        enum:
          - publish
          - future
          - draft
          - pending
          - private
      type:
        description: Type of post.
        type: string
      password:
        description: A password to protect access to the content and excerpt.
        type: string
      permalink_template:
        description: Permalink template for the post.
        type: string
      generated_slug:
        description: Slug automatically generated from the post title.
        type: string
      title:
        description: The title for the post.
        type: object
        properties:
          raw:
            description: Title for the post, as it exists in the database.
            type: string
          rendered:
            description: HTML title for the post, transformed for display.
            type: string
      content:
        description: The content for the post.
        type: object
        properties:
          raw:
            description: Content for the post, as it exists in the database.
            type: string
          rendered:
            description: HTML content for the post, transformed for display.
            type: string
          block_version:
            description: Version of the content block format used by the post.
            type: integer
          protected:
            description: Whether the content is protected with a password.
            type: boolean
      author:
        description: The ID for the author of the post.
        type: integer
      featured_media:
        description: The ID of the featured media for the post.
        type: integer
      menu_order:
        description: The order of the post in relation to other posts.
        type: integer
      format:
        description: The format for the post.
        type: string
        enum:
          - standard
          - aside
          - chat
          - gallery
          - link
          - image
          - quote
          - status
          - video
          - audio
      template:
        description: The theme file to use to display the post.
        type: string
securityDefinitions:
  cookieAuth:
    type: apiKey
    name: X-WP-Nonce
    in: header
    description: Please see http://v2.wp-api.org/guide/authentication/
